language: node_js
node_js:
  - 10.16.3

cache:
  directories:
    - node_modules
before_script:
  - yarn install

script:
  - yarn build
deploy:
  provider: firebase
  edge: true
  only: hosting:production
  on:
    branch: master
  token: $FIREBASE_TOKEN
  message: 'Yooo KB !!! ... KB TechSpace is deployed now'
